version: '3.4'

services:
  catalogdb:
    image: postgres

  basketdb:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4  

  portainer:
    image: portainer/portainer-ce

  catalog.api:  
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile
      
  logcontrol:
    image: ${DOCKER_REGISTRY-}logcontrol
    build:
      context: .
      dockerfile: LogControl/Dockerfile

  
  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: Ocelot.Api/Dockerfile  

  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2


volumes:
  portainer_data:
  postgres_data:
  pgadmin_data:
  elasticsearch-data: